export default {
    products: [
      {
        _id: '1',
        name: 'Crotchet Sling Bag',
        category: 'Bags',
        image: '/images/Bag1.jpg',
        price: 60,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 10,
      },
      {
        _id: '2',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/Bag1.jpg',
        price: 50,
        brand: ' Nike',
        rating: 4.2,
        numReviews: 5,
        countInStock: 6,
      },
      {
        _id: '3',
        name: 'Best Pants',
        category: 'Pants',
        image: '/images/Bag1.jpg',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      }, {
        _id: '4',
        name: 'Best Pants',
        category: 'Pants',
        image: '/images/Bag1.jpg',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
      },
    ]
  }